name: update
on: [push, workflow_dispatch]jobs:
  run:
      runs-on: ubuntu-latest
          steps:
                - uses: actions/checkout@v3
                      - run: python main.py
                              env:
                                        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
                                                  SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
                                                  
