name: update
on: [workflow_dispatch, push]
jobs:
  run:
      runs-on: ubuntu-latest    steps:
            - uses: actions/checkout@v4
                  - run: pip install -r requirements.txt
                        - run: python main.py
                                env:
                                          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
                                                    SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
                                                          - run: |
                                                                    git config user.name "bot"
                                                                              git config user.email "bot@bot.com"
                                                                                        git add .
                                                                                                  git commit -m "up" || exit 0
                                                                                                            git push
                                                                                                            
